/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Andrade <source.compu at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.configuracionVentana();
        // this.setFont(new java.awt.Font("Ubuntu", 0, 18));
    }
    
    // Configuracion de la ventana
    private void configuracionVentana()
    {
        // Tamaño de la ventana
        this.setSize(800, 600);
        // Abrimos la ventana maximizada
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInterno = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemCerrar = new javax.swing.JMenuItem();
        menuItemCerrarTodas = new javax.swing.JMenuItem();
        menuItemInfo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSalir = new javax.swing.JMenuItem();
        menuVentanas = new javax.swing.JMenu();
        menuItemCascada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visor de fotos");
        setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(getMaximumSize());
        getContentPane().add(panelInterno, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(java.awt.Color.lightGray);
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        menuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAbrir.setText("Abrir");
        menuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemAbrir);

        menuItemCerrar.setText("Cerrar");
        menuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemCerrar);

        menuItemCerrarTodas.setText("Cerrar todas");
        menuItemCerrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarTodasActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemCerrarTodas);

        menuItemInfo.setText("Información");
        menuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInfoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemInfo);
        menuArchivo.add(jSeparator1);

        menuItemSalir.setText("Salir");
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuVentanas.setText("Ventanas");

        menuItemCascada.setText("Cascada");
        menuItemCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCascadaActionPerformed(evt);
            }
        });
        menuVentanas.add(menuItemCascada);

        jMenuBar1.add(menuVentanas);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(660, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Menu Item Abrir
    private void menuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirActionPerformed
        // Creamos una ventana para elegir archivos
        JFileChooser file = new JFileChooser();
        
        // Abrimos la ventana y obtenemos el boton pulsado
        int pulsado = file.showOpenDialog(null);
        
        // Verificamos la opcion seleccionada
        if(pulsado == JFileChooser.APPROVE_OPTION){
            // Creamos la ventana interna
            VentanaInterna vi = new VentanaInterna();
            
            // Configuracion de la ventana
            // vi.setResizable(true);
            // vi.setResizable(false);
            vi.setMaximizable(true);
            vi.setIconifiable(true);
            vi.setClosable(true);
            vi.setSize(panelInterno.getWidth(), panelInterno.getHeight());
            
            // Agregamos la ventana al panel principal
            panelInterno.add(vi);
            
            // Obtenemos la imagen
            String path = file.getSelectedFile().toString();
            
            // Pasamos la imagen a la ventana interna
            vi.setImagen(path);
            vi.setTitle(path);
            
            // Mostramos la ventana
            vi.setVisible(true);
            
            // Obtenemos todas las ventanas abiertas
            JInternalFrame v[] = panelInterno.getAllFrames();
            
            // Recorremos las ventanas
            for(int i = 0; i < v.length; i++){
                if(vi.getUIClassID() != v[i].getUIClassID()){
                    v[i].setVisible(false);
                }
            }
            
        }
    }//GEN-LAST:event_menuItemAbrirActionPerformed

    // Boton cerrar
    private void menuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarActionPerformed
        // Obtenemos la ventana activa
        VentanaInterna vActiva = (VentanaInterna) panelInterno.getSelectedFrame();
        
        // Verificamos que si exista la venta activa
        if(vActiva != null){
            // Cerramos la ventana
            vActiva.dispose();
        }
    }//GEN-LAST:event_menuItemCerrarActionPerformed

    // Mostramos informacion
    private void menuItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInfoActionPerformed
        // Obtenemos ventana activa
        VentanaInterna vInterna = (VentanaInterna) panelInterno.getSelectedFrame();
        
        // Verificamos si esta activa
        if(vInterna != null){
            String path = vInterna.getTitle();
            JOptionPane.showMessageDialog(null, "Camino de la imagen: "+path);
        } else {
            JOptionPane.showMessageDialog(null, "No hay ninguna ventana activa");
        }
    }//GEN-LAST:event_menuItemInfoActionPerformed

    // Boton cerrar todas
    private void menuItemCerrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarTodasActionPerformed
        // Obtenemos todas las ventanas
        JInternalFrame vInternas[] = panelInterno.getAllFrames();
        
        // Recorremos el array
        for(int i = 0; i < vInternas.length; i++){
            if(vInternas[i] != null){
                vInternas[i].dispose();
            }
        }
    }//GEN-LAST:event_menuItemCerrarTodasActionPerformed

    // Menu ventana -> cascada
    private void menuItemCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCascadaActionPerformed
        // Obtenemos las ventanas abiertas
        JInternalFrame v[] = panelInterno.getAllFrames();
        int x = 0, y = 0; // Posicion de la ventana
        
        // Recorremos las ventanas
        for(int i = 0; i < v.length; i++){
            v[i].setLocation(x, y);
            
            x += 30;
            y += 30;
        }
    }//GEN-LAST:event_menuItemCascadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
         * Plantilla por defecto: Nimbus
         * Otras plantillas: Metal, Windows
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemCascada;
    private javax.swing.JMenuItem menuItemCerrar;
    private javax.swing.JMenuItem menuItemCerrarTodas;
    private javax.swing.JMenuItem menuItemInfo;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuVentanas;
    private javax.swing.JDesktopPane panelInterno;
    // End of variables declaration//GEN-END:variables
}
