/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Andrade <source.compu at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame
{
    SalaCine _central; // Sala de cine central
    SalaCine _vo; // Sala de cine versiones originales
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        // Inicializamos las salas de cine
        this._central = new SalaCine();
        this._vo = new SalaCine();
        
        // Configuramos las salas
        this._central.setAforo(500);
        this._central.setEntrada(8.0);
        this._vo.setAforo(80);
        this._vo.setEntrada(6.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCentralCambiar = new javax.swing.JButton();
        btnCentralNueva = new javax.swing.JButton();
        btnCentralOcupacion = new javax.swing.JButton();
        btnCentralVaciar = new javax.swing.JButton();
        btnCentralIngresos = new javax.swing.JButton();
        lblCentralPelicula = new javax.swing.JLabel();
        panelVOriginal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVOriginalCambiar = new javax.swing.JButton();
        btnVOriginalNueva = new javax.swing.JButton();
        btnVOriginalOcupacion = new javax.swing.JButton();
        btnVOriginalVaciar = new javax.swing.JButton();
        btnVOriginalIngresos = new javax.swing.JButton();
        lblVOriginalPelicula = new javax.swing.JLabel();
        btnIngresoTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multicinemas");

        panelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("SALA CENTRAL");

        jLabel3.setText("Película");

        btnCentralCambiar.setText("Cambiar");
        btnCentralCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralCambiarActionPerformed(evt);
            }
        });

        btnCentralNueva.setText("Nueva Venta");
        btnCentralNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralNuevaActionPerformed(evt);
            }
        });

        btnCentralOcupacion.setText("% Ocupación");
        btnCentralOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralOcupacionActionPerformed(evt);
            }
        });

        btnCentralVaciar.setText("Vaciar");
        btnCentralVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralVaciarActionPerformed(evt);
            }
        });

        btnCentralIngresos.setText("Ingresos");
        btnCentralIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralIngresosActionPerformed(evt);
            }
        });

        lblCentralPelicula.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCentralPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnCentralCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(btnCentralNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCentralOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCentralVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCentralIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCentralCambiar)
                    .addComponent(lblCentralPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCentralNueva)
                    .addComponent(btnCentralOcupacion)
                    .addComponent(btnCentralVaciar)
                    .addComponent(btnCentralIngresos))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelVOriginal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("SALA VERSIÓN ORIGINAL");

        jLabel4.setText("Película");

        btnVOriginalCambiar.setText("Cambiar");
        btnVOriginalCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVOriginalCambiarActionPerformed(evt);
            }
        });

        btnVOriginalNueva.setText("Nueva Venta");
        btnVOriginalNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVOriginalNuevaActionPerformed(evt);
            }
        });

        btnVOriginalOcupacion.setText("% Ocupación");
        btnVOriginalOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVOriginalOcupacionActionPerformed(evt);
            }
        });

        btnVOriginalVaciar.setText("Vaciar");
        btnVOriginalVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVOriginalVaciarActionPerformed(evt);
            }
        });

        btnVOriginalIngresos.setText("Ingresos");
        btnVOriginalIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVOriginalIngresosActionPerformed(evt);
            }
        });

        lblVOriginalPelicula.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelVOriginalLayout = new javax.swing.GroupLayout(panelVOriginal);
        panelVOriginal.setLayout(panelVOriginalLayout);
        panelVOriginalLayout.setHorizontalGroup(
            panelVOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVOriginalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelVOriginalLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVOriginalPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnVOriginalCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVOriginalLayout.createSequentialGroup()
                        .addComponent(btnVOriginalNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVOriginalOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVOriginalVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVOriginalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelVOriginalLayout.setVerticalGroup(
            panelVOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVOriginalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelVOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnVOriginalCambiar)
                    .addComponent(lblVOriginalPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(panelVOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVOriginalNueva)
                    .addComponent(btnVOriginalOcupacion)
                    .addComponent(btnVOriginalVaciar)
                    .addComponent(btnVOriginalIngresos))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        btnIngresoTotal.setText("Ingresos Totales");
        btnIngresoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIngresoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelVOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnIngresoTotal)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Verificamos si la sala tiene asignada una pelicula
    private boolean checarSala(SalaCine temp)
    {
        // Verificamos
        return !temp.getPelicula().isEmpty();
    }
    
    // Boton cambiar pelicula sala central
    private void btnCentralCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralCambiarActionPerformed
        // Variables a utilizar
        String titulo = "";
        
        // Obtenemos el titulo de la pelicula
        titulo = JOptionPane.showInputDialog(null, "Ingrese el titulo de la película: ");
        
        // Verificamos que se ingreso un titulo
        if(!titulo.isEmpty()){
            // Formateaamos el titulo
            titulo = titulo.toUpperCase();
            
            // Cambiamos el titulo de la pelicula
            this._central.setPelicula(titulo);
            
            // Mostramos la nueva pelicula
            lblCentralPelicula.setText(titulo);
        }
    }//GEN-LAST:event_btnCentralCambiarActionPerformed
    
    // Boton cambiar pelicula sala version original
    private void btnVOriginalCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVOriginalCambiarActionPerformed
        // Variables a utilizar
        String titulo = new String("");
        
        // Obtenemos el titulo de la pelicula
        titulo = JOptionPane.showInputDialog(null, "Ingrese el titulo de la película: ");
        
        // Verificamos que se ingreso un titulo
        if(!titulo.isEmpty()){
            // Formateaamos el titulo
            titulo = titulo.toUpperCase();
            
            // Cambiamos el titulo de la pelicula
            this._vo.setPelicula(titulo);
            
            // Mostramos la nueva pelicula
            lblVOriginalPelicula.setText(titulo);
        }
    }//GEN-LAST:event_btnVOriginalCambiarActionPerformed

    // Boton nueva entrada sala central
    private void btnCentralNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralNuevaActionPerformed
        // Verificamos que tenga pelicula la sala
        if(checarSala(this._central)){
            // ingresamos un cliente
            if(this._central.entraUno()){
                JOptionPane.showMessageDialog(null, "Entrada registrada");
            } else {
                JOptionPane.showMessageDialog(null, "Sala llena", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar una película primero", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCentralNuevaActionPerformed

    // Boton nueva entrada sala version original
    private void btnVOriginalNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVOriginalNuevaActionPerformed
        // Verificamos que tenga pelicula la sala
        if(checarSala(this._vo)){
            // ingresamos un cliente
            if(this._vo.entraUno()){
                JOptionPane.showMessageDialog(null, "Entrada registrada");
            } else {
                JOptionPane.showMessageDialog(null, "Sala llena", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar una película primero", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVOriginalNuevaActionPerformed

    // Boton % ocupacion sala central
    private void btnCentralOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralOcupacionActionPerformed
        // Variable a utilizar
        String info;
        
        // Verificamos que tenga pelicula la sala
        if(checarSala(this._central)){
            // Configuracion de la informacion a mostrar
            info = "Pelicula: "+this._central.getPelicula()+"\n";
            info += "Aforo total: "+this._central.getAforo()+"\n";
            info += "Asientos ocupados: "+this._central.getOcupadas()+"\n";
            info += "Asientos libres: "+this._central.getLibres()+"\n";
            info += "Ocupación: "+this._central.getPorcentajes()+"%";
            
            // Mostramos la informacion
            JOptionPane.showMessageDialog(null, info);
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar una película primero", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCentralOcupacionActionPerformed

    // Boton % ocupacion sala version original
    private void btnVOriginalOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVOriginalOcupacionActionPerformed
        // Variable a utilizar
        String info;
        
        // Verificamos que tenga pelicula la sala
        if(checarSala(this._vo)){
            // Configuracion de la informacion a mostrar
            info = "Pelicula: "+this._vo.getPelicula()+"\n";
            info += "Aforo total: "+this._vo.getAforo()+"\n";
            info += "Asientos ocupados: "+this._vo.getOcupadas()+"\n";
            info += "Asientos libres: "+this._vo.getLibres()+"\n";
            info += "Ocupación: "+this._vo.getPorcentajes()+"%";
            
            // Mostramos la informacion
            JOptionPane.showMessageDialog(null, info);
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar una película primero", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVOriginalOcupacionActionPerformed
    
    // Boton vaciar sala central
    private void btnCentralVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralVaciarActionPerformed
        // Limpiamos la informacion
        this._central.vaciar();
        
        // Limpiamos la pelicula
        lblCentralPelicula.setText("");
    }//GEN-LAST:event_btnCentralVaciarActionPerformed

    // Boton vaciar sala version original
    private void btnVOriginalVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVOriginalVaciarActionPerformed
        // Limpiamos la informacion
        this._vo.vaciar();
        
        // Limpiamos la pelicula
        lblVOriginalPelicula.setText("");
    }//GEN-LAST:event_btnVOriginalVaciarActionPerformed

    // Boton ingresos sala central
    private void btnCentralIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralIngresosActionPerformed
        // Variables a utilizar
        String info;

        // Verificamos que tenga pelicula la sala
        if(checarSala(this._central)){
            // Configuramos la informacion
            info = "Ingresos de sala central: $"+this._central.getIngresos();

            // Mostramos la informacion
            JOptionPane.showMessageDialog(null, info);
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar una película primero", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCentralIngresosActionPerformed

    // Boton ingresos sala version original
    private void btnVOriginalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVOriginalIngresosActionPerformed
        // Variables a utilizar
        String info;

        // Verificamos que tenga pelicula la sala
        if(checarSala(this._vo)){
            // Configuramos la informacion
            info = "Ingresos de sala central: $"+this._vo.getIngresos();

            // Mostramos la informacion
            JOptionPane.showMessageDialog(null, info);
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar una película primero", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVOriginalIngresosActionPerformed

    // Boton ingresos totales
    private void btnIngresoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoTotalActionPerformed
        // Variables a utilizar
        String info;

        // Verificamos que tenga pelicula la sala
        if(checarSala(this._vo) || checarSala(this._central)){
            // Configuramos la informacion
            info = "Ingresos totales: $"+(this._vo.getIngresos() + this._central.getIngresos());

            // Mostramos la informacion
            JOptionPane.showMessageDialog(null, info);
        } else {
            // Mostramos error
            JOptionPane.showMessageDialog(null, "Debe registrar por lo menos una película", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresoTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentralCambiar;
    private javax.swing.JButton btnCentralIngresos;
    private javax.swing.JButton btnCentralNueva;
    private javax.swing.JButton btnCentralOcupacion;
    private javax.swing.JButton btnCentralVaciar;
    private javax.swing.JButton btnIngresoTotal;
    private javax.swing.JButton btnVOriginalCambiar;
    private javax.swing.JButton btnVOriginalIngresos;
    private javax.swing.JButton btnVOriginalNueva;
    private javax.swing.JButton btnVOriginalOcupacion;
    private javax.swing.JButton btnVOriginalVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCentralPelicula;
    private javax.swing.JLabel lblVOriginalPelicula;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelVOriginal;
    // End of variables declaration//GEN-END:variables
}
