
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paulo Andrade <source.compu at gmail.com>
 */
public class NuevaVentana extends javax.swing.JFrame
{
    // Propiedades
    JCheckBox vCuadros[];
    JButton btnAceptar;

    /**
     * Creates new form NuevaVentana
     */
    public NuevaVentana() {
        vCuadros = new JCheckBox[10]; // Inicializamos el array
        btnAceptar = new JButton();
        initComponents();
        creacionVentana(); // Ventana principal
    }
    
    // Ventana principal
    private void creacionVentana()
    {
        // Caracteristicas de la ventana
        this.setTitle("Vectores");
        this.setSize(300, 600);
        
        // Inicializamos los elementos del vector
        String vTextos[] = {"Rojo", "Azul", "Verde", "Amarillo", "Rosa",
            "Naranja", "Magenta", "Marron", "Gris", "Morado"};
        for (int i = 0; i < vCuadros.length; i++) {
            // Inicalizamos cada elemento
           vCuadros[i] = new JCheckBox();
           vCuadros[i].setText(vTextos[i]);
           vCuadros[i].setBounds(10, 10 + 30*i,100, 20);
           this.getContentPane().add(vCuadros[i]);
        }
        
        // Configuracion del boton aceptar
        btnAceptar.setText("Aceptar");
        btnAceptar.setBounds(10, 360, 100, 20);
        this.getContentPane().add(btnAceptar);
        btnAceptar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
    }
    
    // Evento del boton aceptar
    public void btnAceptarActionPerformed(ActionEvent evt)
    {
        // Variables a utilizar
        int count = 0; // Contador
        
        // Verificamos cuantos cuadros seleccionados hay
        for(int i = 0; i < vCuadros.length; i++){
            if(vCuadros[i].isSelected()){
                count++;
            }
        }
        
        // Mostramos mensaje
        if(count == 1){
            JOptionPane.showMessageDialog(null, "Hay "+count+" cuadro seleccionado.");
        } else {
            JOptionPane.showMessageDialog(null, "Hay "+count+" cuadros seleccionados.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
