/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Andrade <source.compu at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame
{
    BotonContador btnBotonA;
    BotonContador btnBotonB;
    BotonContador btnBotonC;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.creacionVentana();
    }
    
    // Configuracion ventana principal
    private void creacionVentana()
    {
        this.setTitle("Boton contador");
        this.setLocationRelativeTo(null);
        // this.setSize(250, 300);
        
        // Configuramos el boton A
        btnBotonA = new BotonContador();
        btnBotonA.setText("Boton A");
        btnBotonA.setBounds(10, 10, 100, 30);
        this.getContentPane().add(btnBotonA);
        
        // Configuramos el boton B
        btnBotonB = new BotonContador();
        btnBotonB.setText("Boton B");
        btnBotonB.setBounds(130, 10, 100, 30);
        this.getContentPane().add(btnBotonB);
        
        btnBotonC = new BotonContador();
        btnBotonC.setText("Boton C");
        btnBotonC.setBounds(250, 10, 100, 30);
        this.getContentPane().add(btnBotonC);
        
        // Evento para el boton A
        btnBotonA.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt)
            {
                btnBotonAActionPerformed(evt);
            }
        });
        
        // Evento para el boton B
        btnBotonB.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt)
            {
                btnBotonBActionPerformed(evt);
            }
        });
        
        // Evento para el boton C
        btnBotonC.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt)
            {
                btnBotonCActionPerformed(evt);
            }
        });
    }
    
    // Action performed boton A
    public void btnBotonAActionPerformed(ActionEvent evt)
    {
        // Incrementamos el contador del boton
        btnBotonA.incrementa();
    }
    
    // Action performed boton B
    public void btnBotonBActionPerformed(ActionEvent evt)
    {
        // Incrementamos el contador del boton
        btnBotonB.incrementa();
    }
    
    // Action performed boton C
    public void btnBotonCActionPerformed(ActionEvent evt)
    {
        // Incrementamos el contador del boton
        btnBotonC.aumentar(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVer = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        txtBoton = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVer.setText("Ver pulsaciones");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtBoton)
                    .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer)
                    .addComponent(btnReiniciar))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton ver pulsaciones
    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // variables a utilizar
        String info;
        
        // Configuramos el contenido
        info = "Pulsaciones boton A: "+btnBotonA.getPulsaciones()+"\n";
        info += "Pulsaciones boton B: "+btnBotonB.getPulsaciones()+"\n";
        info += "Pulsaciones boton C: "+btnBotonC.getPulsaciones();
        
        // Mostramos la informacion
        JOptionPane.showMessageDialog(null, info);
    }//GEN-LAST:event_btnVerActionPerformed

    // Boton reiniciar
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // Reiniciamos los botones
        btnBotonA.reinicia();
        btnBotonB.reinicia();
        btnBotonC.reinicia();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    // Boton iniciar
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // Variables a utilizar
        Integer pulsaciones;
        
        // Verificamos que no este vacio
        if(txtBoton.getText().length() > 0){
            // Obtenemos la cantidad a aumentar
            pulsaciones = Integer.parseInt(txtBoton.getText());
        
            // Inicializamos los botones
            btnBotonA.setPulsaciones(pulsaciones);
            btnBotonB.setPulsaciones(pulsaciones);
            btnBotonC.setPulsaciones(pulsaciones);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVer;
    private javax.swing.JTextField txtBoton;
    // End of variables declaration//GEN-END:variables
}
