
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paulo Andrade <source.compu at gmail.com>
 */
public class NuevaVentana extends javax.swing.JFrame
{
    // Propiedades
    JButton vBotones[];

    /**
     * Creates new form NuevaVentana
     */
    public NuevaVentana() {
        vBotones = new JButton[5];
        initComponents();
        creacionVentana();
    }
    
    // Ventana principal
    private void creacionVentana()
    {
        // Carateristicas de la ventana
        this.setTitle("Vectores y eventos");
        this.setSize(600, 200);
        
        String vTextos[] = {"Aceptar", "Cancelar", "Aplicar", "Cerrar", "Salir"};
        
        // Configutramos el array de botones
        for(int i = 0; i < vBotones.length; i++){
            vBotones[i] = new JButton();
            vBotones[i].setText(vTextos[i]);
            vBotones[i].setBounds(10 + i * 100, 100, 90, 20);
            
            this.getContentPane().add(vBotones[i]);
        }
        
        // Configuramos los eventos
        for(int i = 0; i < vBotones.length; i++){
            vBotones[i].addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent evt){
                    botonActionPerformed(evt);
                }
            });
        }
    }
    
    // evento para botones
    public void botonActionPerformed(ActionEvent evt){
        // Obtenemos el boton seleccionado
        JButton boton = (JButton) evt.getSource();
        
        // Mostramos mensaje
        JOptionPane.showMessageDialog(null, "Has seleccionado el boton " + boton.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
