/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Paulo Andrade <source.compu at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame
{
    JLabel lblNum1;
    JLabel lblNum2;
    JTextField txtNum1;
    JTextField txtNum2;
    JButton btnSumar;
    JButton btnRestar;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        creacionVentana();
    }
    
    /**
     * Creamos la ventana principal
     */
    public void creacionVentana()
    {
        // Mediante this hacemos referencia a la ventana
        this.setTitle("Programa operaciones"); // Titulo de la ventana
        this.setSize(500, 300); // Tamaño de la ventana
        this.setLocationRelativeTo(null); // Centramos respecto a la pantalla
        
        // Configuramos la etiqueta lblNum1
        lblNum1 = new JLabel();
        lblNum1.setText("Número 1:"); // Texto de la etiqueta
        // setBounds(pos x, pos y, width, height)
        lblNum1.setBounds(10, 10, 100, 20); // posicion y tamaño
        this.getContentPane().add(lblNum1); // Añadimos la etiqueta
        
        // Configuramos la etiqueta lblNum2
        lblNum2 = new JLabel();
        lblNum2.setText("Número 2:"); // Texto de la etiqueta
        // setBounds(pos x, pos y, width, height)
        lblNum2.setBounds(10, 60, 100, 20); // posicion y tamaño
        this.getContentPane().add(lblNum2); // Añadimos la etiqueta
        
        // Configuramos el cuadro de texto txtNum1
        txtNum1 = new JTextField();
        txtNum1.setText("0"); // Texto del cuadro
        // setBounds(pos x, pos y, width, height)
        txtNum1.setBounds(110, 10, 100, 20); // posicion y tamaño
        this.getContentPane().add(txtNum1); // Añadimos la etiqueta
        
        // Configuramos el cuadro de texto txtNum2
        txtNum2 = new JTextField();
        txtNum2.setText("0"); // Texto del cuadro
        // setBounds(pos x, pos y, width, height)
        txtNum2.setBounds(110, 60, 100, 20); // posicion y tamaño
        this.getContentPane().add(txtNum2); // Añadimos la etiqueta
        
        // Configuramos el boton sumar
        btnSumar = new JButton();
        btnSumar.setText("Sumar");
        // setBounds(pos x, pos y, width, height)
        btnSumar.setBounds(10, 120, 100, 20); // posicion y tamaño
        this.getContentPane().add(btnSumar); // Añadimos la etiqueta
        
        // Configuramos el boton restar
        btnRestar = new JButton();
        btnRestar.setText("Restar");
        // setBounds(pos x, pos y, width, height)
        btnRestar.setBounds(150, 120, 100, 20); // posicion y tamaño
        this.getContentPane().add(btnRestar); // Añadimos la etiqueta
        
        // ActionPerformed del boton sumar
        btnSumar.addActionListener(this::btnSumarActionPerformed);
        
        // ActionPerformed del boton restar
        btnRestar.addActionListener(this::btnRestarActionPerformed);
    }
    
    // Metodo action performed de boton sumar
    public void btnSumarActionPerformed(ActionEvent evt){
        // Variables a utilizar
        Double num1, num2, resultado;
        
        // Verificamos que los campos de textos no esten vacios
        if(txtNum1.getText().length() > 0 && txtNum2.getText().length() > 0){
            // Obtenemos los valores
            num1 = Double.parseDouble(txtNum1.getText());
            num2 = Double.parseDouble(txtNum2.getText());
            
            // Hacemos los calculos
            resultado = num1 + num2;

            JOptionPane.showMessageDialog(this, "La suma es: "+resultado);
        }
    }
    
    // Metodo action performed de boton restar
    public void btnRestarActionPerformed(ActionEvent evt){
        // Variables a utilizar
        Double num1, num2, resultado;
        
        // Verificamos que los campos de textos no esten vacios
        if(txtNum1.getText().length() > 0 && txtNum2.getText().length() > 0){
            // Obtenemos los valores
            num1 = Double.parseDouble(txtNum1.getText());
            num2 = Double.parseDouble(txtNum2.getText());
            
            // Hacemos los calculos
            resultado = num1 - num2;

            JOptionPane.showMessageDialog(this, "La resta es: "+resultado);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
